### ISSUE TITLE
gsi通话无法听到对方声音

### ISSUE THREAD

**Issue by ivysrono** [wbs306/device_xiaomi_xaga#2]
中国电信

刷入GSI（包括PHH和Google）

通话无法听到对方声音——单向问题，对方可以听到己方声音。
 
 miui国际版和国内版均无此问题。
 
上一代 chopin D1100 用gsi虽然也不支持volte但未发现此问题。

不知有无解决方案或者思路。

**Comment by ivysrono** [comment]
找到酷安才发现是通病了。

现在刷机还是在酷安这种封闭的地方么……

**Comment by wbs306** [comment]
所以建议不使用gsi, 这里是做了适配的，通话能用。另外包一般会先发在telegram：https://t.me/xagapro
