### ISSUE TITLE
Bug：部分APP状态栏无法正确显示

### ISSUE THREAD

**Issue by ivysrono** [wbs306/device_xiaomi_xaga#3]
ROM：PixelExperience_Plus_xaga-12.1-20220814-0257-UNOFFICIAL

APP：

[BadukAI v1.17.0](https://github.com/aki65/aki65.github.io/releases/tag/v1.17.0)

https://github.com/aki65/aki65.github.io/issues/67

![Screenshot_BadukAI](https://user-images.githubusercontent.com/2649544/182008437-29ea81ff-3ebe-43c9-90cb-8d457c1f1f09.png)

![Screenshot_BadukAI](https://user-images.githubusercontent.com/2649544/182008439-7fff56e7-a371-452f-8034-c4249da9d75a.png)

**Comment by wbs306** [comment]
哪个版本

**Comment by ivysrono** [comment]
ROM：PixelExperience_Plus_xaga-12.1-20220814-0257-UNOFFICIAL

**Comment by wbs306** [comment]
我这里显示没有你截图的显示不全。另外如果你是指上面有黑条，那是因为miui强制全屏了，如果你想去掉的话，可以在开发者选项-刘海屏模拟里面选择NotchKiller

**Comment by ivysrono** [comment]
下面这图是 Chopin 上 GSI 的显示情况，可以看到相比之下，xaga 顶部和底部各被吃掉了一部分。

刘海屏模拟不能彻底解决显示不完整的问题。

![Screenshot_20220814-221314](https://user-images.githubusercontent.com/2649544/184541004-c7c3e61b-4f3d-4025-952a-4d514ed39e50.png)

**Comment by wbs306** [comment]
关闭导航条可以解决，估计是底部的叠加层没写好，之前是写了状态栏的，有空我再看看

**Comment by kartikbanwala1** [comment]
Hey bro , U have telegram account?

**Comment by ivysrono** [comment]
`DerpFest-13-Community-Tango-xaga-20230122-1406` fixed.
