### ISSUE TITLE
Bug：腾讯系APP在WorkProfile闪退

### ISSUE THREAD

**Issue by ivysrono** [wbs306/device_xiaomi_xaga#5]
`DerpFest-13-Community-Tango-xaga-20230122-1406`

[Shelter | F-Droid - Free and Open Source Android App Repository](https://f-droid.org/packages/net.typeblog.shelter/)

[Insular | F-Droid - Free and Open Source Android App Repository](https://f-droid.org/packages/com.oasisfeng.island.fdroid/)

微信 8.0.32

TIM 3.5.0

通过Shelter创建的WP中，微信打开即闪退，TIM登录后很快闪退；

通过Insular创建的WP中，微信多次闪退后得以登录，TIM同样登录后很快闪退。

支付宝等APP无闪退现象。

腾讯系APP安装在主用户中同样正常运行。

**Comment by wbs306** [comment]
Android13的Miui能用吗

**Comment by ivysrono** [comment]
miui14.0.2安装shelter后，miui系统禁止克隆非系统应用。

**Comment by wbs306** [comment]
那你在miui里开gsi看看有没有问题，这个问题和device tree的关系不大，多和应用适配有关

**Comment by ivysrono** [comment]
经测试多个GSI（附后），其共性问题是无法安装[weixin8032android2300_arm64_3.apk](https://weixin.qq.com/)，原因不明。但其他腾讯系APP（TIM等）均可以正常运行。
没有找到DerpFest的GSI，难以判断是DerpFest本身的问题还是device tree的问题。
测试GSI清单：
[SparkOS-13.4-arm64_bvN-Unofficial.img.xz](https://sourceforge.net/projects/gsi-projects/files/A13/SparkOS/16012023/SparkOS-13.4-arm64_bvN-Unofficial.img.xz/download)
[crDroid-9.1-arm64_bvN-Unofficial.img.xz](https://sourceforge.net/projects/gsi-projects/files/A13/crDroid/15012023/crDroid-9.1-arm64_bvN-Unofficial.img.xz/download)
[ArrowOS-13.0-arm64_bvN-Unofficial.img.xz](https://sourceforge.net/projects/gsi-projects/files/A13/ArrowOS/08012023/ArrowOS-13.0-arm64_bvN-Unofficial.img.xz/download)
[lineage-20.0-20230115-UNOFFICIAL-arm64_bvN-vndklite.img.xz](https://sourceforge.net/projects/andyyan-gsi/files/lineage-20-td/lineage-20.0-20230115-UNOFFICIAL-arm64_bvN-vndklite.img.xz/download)
[lineage-20.0-20230109-UNOFFICIAL-gsi_arm64_vN.img.xz](https://sourceforge.net/projects/andyyan-gsi/files/lineage-20-light/lineage-20.0-20230109-UNOFFICIAL-gsi_arm64_vN.img.xz/download)
[Release android_13.0.0_r24 ci-20230131 · TrebleDroid/treble_experimentations](https://github.com/TrebleDroid/treble_experimentations/releases/tag/ci-20230131)

**Comment by wbs306** [comment]
我这边在crDroid上测试了，微信和Tim都可以正常使用，没有闪退。可以排除是device tree的问题。

**Comment by ivysrono** [comment]
试试这个看：[政务微信](https://zwwx.wuhan.gov.cn/)
我这启动直接闪退。
GSI上没问题。

**Comment by wbs306** [comment]
经测试也是没有闪退

**Comment by ivysrono** [comment]
这就奇怪了，我这都已经全盘格式化重装了，政务微信只要装在Shelter里就会闪退……

**Comment by ivysrono** [comment]
麻烦再试试这个：[政务微信](https://wx.bigdata.wuxi.gov.cn:10443/)

**Comment by wbs306** [comment]
vanilla? 有没有装gapps

**Comment by ivysrono** [comment]
vanilla，没装gapps，备用机测试，已经不装WorkProfile管理器以外的第三方软件了。
微信什么的确实有时无法重现闪退，前面那个政务微信确实有时也好，但这个[政务微信](https://wx.bigdata.wuxi.gov.cn:10443/)版本似乎反复闪退没有正常启动过。

**Comment by wbs306** [comment]
这个问题不在device tree的范围内了，具体原因可以去shelter等仓库讨论

**Comment by ivysrono** [comment]
问题是在别的手机的第三方rom甚至GSI上都无法复现……

**Comment by wbs306** [comment]
我这边没有闪退问题，我让另一个用derpfest的也去测试了，他也没有问题

**Comment by ivysrono** [comment]
那我再自己想办法测试看看。
抱歉打扰了这么久。

**Comment by ivysrono** [comment]
[Release Lineage-OS-A13 · YadavMohit19/Releases](https://github.com/YadavMohit19/Releases/releases/tag/20230209) 就没有这个问题……无奈👐
