### ISSUE TITLE
Prebuilt vendor

### ISSUE THREAD

**Issue by priiii08918** [wbs306/device_xiaomi_xaga#8]
Hey Wbs !
How can we use prebuilt vendor ? and if you tried it earlier then what were the issues ? We tried gsi over miui and only issue was GPU. Even telegram or other apps camera memory leak issue doesn't exist

**Comment by wbs306** [comment]
If you want to use prebuilt vendor, you can switch to branch 12.1, and bring up to a13. I just wanted to try the oss build before, so I gave up prebuilt vendor. I think the camera problem is related to the vndk version, so using the prebuilt vendor can solve this problem.

**Comment by priiii08918** [comment]
> If you want to use prebuilt vendor, you can switch to branch 12.1, and bring up to a13. I just wanted to try the oss build before, so I gave up prebuilt vendor. I think the camera problem is related to the vndk version, so using the prebuilt vendor can solve this problem.

Thanks for the reply and help

**Comment by priiii08918** [comment]
> If you want to use prebuilt vendor, you can switch to branch 12.1, and bring up to a13. I just wanted to try the oss build before, so I gave up prebuilt vendor. I think the camera problem is related to the vndk version, so using the prebuilt vendor can solve this problem.

So no way we can fix cams without prebuilt vendor ?

**Comment by wbs306** [comment]
yes, idk how to fix it....

**Comment by wbs306** [comment]
Notice that some camera related binary files need patch in a14, have you try patch them in a13? I think this will fix the camera issue. I don't have time to try it....

**Comment by priiii08918** [comment]
> Notice that some camera related binary files need patch in a14, have you try patch them in a13? I think this will fix the camera issue. I don't have time to try it....

we didnt try

**Comment by ChrisCatto** [comment]
> Notice that some camera related binary files need patch in a14, have you try patch them in a13? I think this will fix the camera issue. I don't have time to try it....

It didn't change anything, same issue.
